# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inventario_pb2 as inventario__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inventario_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventarioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AgregarDonacion = channel.unary_unary(
                '/inventario.InventarioService/AgregarDonacion',
                request_serializer=inventario__pb2.DonacionRequest.SerializeToString,
                response_deserializer=inventario__pb2.Respuesta.FromString,
                _registered_method=True)
        self.ModificarDonacion = channel.unary_unary(
                '/inventario.InventarioService/ModificarDonacion',
                request_serializer=inventario__pb2.DonacionRequest.SerializeToString,
                response_deserializer=inventario__pb2.Respuesta.FromString,
                _registered_method=True)
        self.ListarDonaciones = channel.unary_unary(
                '/inventario.InventarioService/ListarDonaciones',
                request_serializer=inventario__pb2.Empty.SerializeToString,
                response_deserializer=inventario__pb2.DonacionesResponse.FromString,
                _registered_method=True)
        self.BajaDonacion = channel.unary_unary(
                '/inventario.InventarioService/BajaDonacion',
                request_serializer=inventario__pb2.DonacionIdRequest.SerializeToString,
                response_deserializer=inventario__pb2.Respuesta.FromString,
                _registered_method=True)


class InventarioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AgregarDonacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModificarDonacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarDonaciones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BajaDonacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventarioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AgregarDonacion': grpc.unary_unary_rpc_method_handler(
                    servicer.AgregarDonacion,
                    request_deserializer=inventario__pb2.DonacionRequest.FromString,
                    response_serializer=inventario__pb2.Respuesta.SerializeToString,
            ),
            'ModificarDonacion': grpc.unary_unary_rpc_method_handler(
                    servicer.ModificarDonacion,
                    request_deserializer=inventario__pb2.DonacionRequest.FromString,
                    response_serializer=inventario__pb2.Respuesta.SerializeToString,
            ),
            'ListarDonaciones': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarDonaciones,
                    request_deserializer=inventario__pb2.Empty.FromString,
                    response_serializer=inventario__pb2.DonacionesResponse.SerializeToString,
            ),
            'BajaDonacion': grpc.unary_unary_rpc_method_handler(
                    servicer.BajaDonacion,
                    request_deserializer=inventario__pb2.DonacionIdRequest.FromString,
                    response_serializer=inventario__pb2.Respuesta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventario.InventarioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventario.InventarioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventarioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AgregarDonacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/AgregarDonacion',
            inventario__pb2.DonacionRequest.SerializeToString,
            inventario__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModificarDonacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/ModificarDonacion',
            inventario__pb2.DonacionRequest.SerializeToString,
            inventario__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarDonaciones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/ListarDonaciones',
            inventario__pb2.Empty.SerializeToString,
            inventario__pb2.DonacionesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BajaDonacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/BajaDonacion',
            inventario__pb2.DonacionIdRequest.SerializeToString,
            inventario__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
